#ifndef __DT_BINDINGS_S32G_APTIV_PINCTRL_H__
#define __DT_BINDINGS_S32G_APTIV_PINCTRL_H__

/* Aptiv CVC Configuration*/
/*
 * Use to set PAD control
 */
#include "s32-gen1-pinctrl.h"

#define PAD_CTL_UART_LIN_TX		(PAD_CTL_SRE_100MHZ | PAD_CTL_OBE | \
				 PAD_CTL_SRC_SIG_SEL3)
#define PAD_CTL_UART0_LIN_TX		(PAD_CTL_SRE_100MHZ | PAD_CTL_OBE | \
				 PAD_CTL_SRC_SIG_SEL1)
#define PAD_CTL_UART_RX_LIN_IMCR	(PAD_CTL_SRC_SIG_SEL2)

/* UART0 configuration */
#define S32_GEN1_PAD_PC09__UART0_TXD_OUT	41	PAD_CTL_UART0_LIN_TX
#define S32_GEN1_PAD_PC10__UART0_RXD_OUT	42	PAD_CTL_UART_RX_MSCR
#define S32_GEN1_PAD_PC10__UART0_RXD_IN		512	PAD_CTL_UART_RX_LIN_IMCR

/* UART1 configuration */
#define S32_GEN1_PAD_PC08__UART1_TXD_OUT	40	PAD_CTL_UART_TX
#define S32_GEN1_PAD_PC04__UART1_RXD_OUT	36	PAD_CTL_UART_RX_MSCR
#define S32_GEN1_PAD_PC04__UART1_RXD_IN		736	PAD_CTL_UART_RX_IMCR

/* UART2 configuration */
#define S32_GEN1_PAD_PB11__UART2_TXD_OUT	27	PAD_CTL_UART_LIN_TX
#define S32_GEN1_PAD_PB12__UART2_RXD_OUT	28	PAD_CTL_UART_RX_MSCR
#define S32_GEN1_PAD_PB12__UART2_RXD_IN		737	PAD_CTL_UART_RX_LIN_IMCR

/* CAN1 configuration */
#define S32_GEN1_PAD_PB03__CAN1_TXD			19	(PAD_CTL_CAN_TX_MSCRx | \
						 PAD_CTL_SRC_SIG_SEL2)
#define S32_GEN1_PAD_PB04__CAN1_RXD_OUT		20	PAD_CTL_CAN_RX_MSCR
#define S32_GEN1_PAD_PB04__CAN1_RXD_IN		631	PAD_CTL_CAN_RX_IMCR

/* CAN2 configuration */
#define S32_GEN1_PAD_PB11__CAN2_TXD			27	(PAD_CTL_CAN_TX_MSCRx | \
						 PAD_CTL_SRC_SIG_SEL2)
#define S32_GEN1_PAD_PB12__CAN2_RXD_OUT		28	PAD_CTL_CAN_RX_MSCR
#define S32_GEN1_PAD_PB12__CAN2_RXD_IN		632	PAD_CTL_CAN_RX_IMCR

/* CAN3 configuration */
#define S32_GEN1_PAD_PB13__CAN3_TXD			29	(PAD_CTL_CAN_TX_MSCRx | \
						PAD_CTL_SRC_SIG_SEL1)
#define S32_GEN1_PAD_PB14__CAN3_RXD_OUT		30	PAD_CTL_CAN_RX_MSCR
#define S32_GEN1_PAD_PB14__CAN3_RXD_IN		633	PAD_CTL_SRC_SIG_SEL3

#endif /* __DT_BINDINGS_S32G_APTIV_PINCTRL_H__ */
