/* SPDX-License-Identifier: GPL-2.0 */

#ifndef _VMFSNO_H_
#define _VMFSNO_H_

#include <linux/bitops.h>

/* these define the attribute byte as seen by DOS */
#define ARONLY  BIT(0)
#define AHIDDEN BIT(1)
#define ASYSTEM BIT(2)
#define AVOLID  BIT(3)
#define ADIR    BIT(4)
#define AARCH   BIT(5)

/* error classes */
#define SUCCESS 0		/* The request was successful. */
#define ERRDOS 0x01		/* Error is from the core DOS operating */
				/* system set. */
#define ERRSRV 0x02		/* Error is generated by the server network
				 * file manager.
				 */
#define ERRHRD 0x03		/* Error is an hardware error. */
#define ERRCMD 0xFF		/* Command was not in the "VMFS" format. */

/* VMFS X/Open error codes for the ERRdos error class */

#define ERR_BAD_FUNC 1		/* Invalid function (or system call) */
#define ERR_BAD_FILE 2		/* File not found (pathname error) */
#define ERR_BAD_PATH 3		/* Directory not found */
#define ERR_NO_FIDS 4		/* Too many open files */
#define ERR_NO_ACCESS 5		/* Access denied */
#define ERR_BAD_FID 6		/* Invalid fid */
#define ERR_BAD_MCB 7		/* Memory control blocks destroyed */
#define ERR_NO_MEM 8		/* Out of memory */
#define ERR_BAD_MEM 9		/* Invalid memory block address */
#define ERR_BAD_ENV 10		/* Invalid environment */
#define ERR_BAD_FORMAT 11		/* Invalid format */
#define ERR_BAD_ACCESS 12		/* Invalid open mode */
#define ERR_BAD_DATA 13		/* Invalid data (only from ioctl call) */
#define ERR_RES 14		/* reserved */
#define ERR_BAD_DRIVE 15		/* Invalid drive */
#define ERR_REM_CD 16		/* Attempt to delete current directory */
#define ERR_DIFF_DEVICE 17	/* rename/move across different filesystems */
#define ERR_NO_FILES 18		/* no more files found in file search */
#define ERR_BAD_SHARE 32		/* Share mode on file conflicts */
				/* with open mode */
#define ERR_LOCK 33		/* Lock request conflicts with existing lock */
#define ERR_FILE_EXISTS 80		/* File in operation already exists */
#define ERR_BAD_PIPE 230		/* Named pipe invalid */
#define ERR_PIPE_BUSY 231		/* All instances of pipe are busy */
#define ERR_PIPE_CLOSING 232	/* named pipe close in progress */
#define ERR_NOT_CONNECTED 233	/* No process on other end of named pipe */
#define ERR_MORE_DATA 234		/* More data to be returned */

#define ERROR_INVALID_PARAMETER  87
#define ERROR_DISK_FULL     112
#define ERROR_INVALID_NAME  123
#define ERROR_DIR_NOT_EMPTY 145
#define ERROR_NOT_LOCKED    158
#define ERROR_ALREADY_EXISTS    183	/* see also 80 ? */
#define ERROR_EAS_NOT_SUPPORTED 282	/* Extended attributes not supported */

/* Error codes for the ERRSRV class */

#define ERR_ERROR 1	/* Non specific error code */
#define ERR_BAD_PW 2	/* Bad password */
#define ERR_BAD_TYPE 3	/* reserved */
#define ERR_ACCESS 4	/* No permissions to do requested operation */
#define ERR_INV_NID 5	/* tid invalid */
#define ERR_INV_NET_NAME 6  /* Invalid servername */
#define ERR_INV_DEVICE 7    /* Invalid device */
#define ERR_Q_FULL 49	    /* Print queue full */
#define ERR_Q_TOO_BIG 50    /* Queued item too big */
#define ERR_INV_PFID 52	    /* Invalid print file in vmfs_fid */
#define ERR_VMFS_CMD 64	    /* Unrecognised command */
#define ERR_SRV_ERROR 65    /* vmfs server internal error */
#define ERR_FILE_SPECS 67   /* fid and pathname invalid combination */
#define ERR_BAD_LINK 68	    /* reserved */
#define ERR_BAD_PERMITS 69 /* Access specified for a file is not valid */
#define ERR_BAD_PID 70	   /* reserved */
#define ERR_SET_ATTR_MODE 71	/* attribute mode invalid */
#define ERR_PAUSED 81		/* Message server paused */
#define ERR_MSG_OFF 82		/* Not receiving messages */
#define ERR_NO_ROOM 83		/* No room for message */
#define ERR_RMUNS 87		/* too many remote usernames */
#define ERR_TIMEOUT 88		/* operation timed out */
#define ERR_NO_RESOURCE  89 /* No resources currently avail for request.*/
#define ERR_TOO_MANU_UIDS 90	/* too many userids */
#define ERR_BAD_UID 91		/* bad userid */
#define ERR_USE_MPX 250	/* temp unable to use raw mode, use MPX mode */
#define ERR_USE_STD 251	/* temp unable to use raw mode, use std.mode */
#define ERR_CONT_MPX 252	/* resume MPX mode */
#define ERR_NO_SUPPORT 0xFFFF	/*  */

/* Error codes for the ERRHRD class */

#define ERR_NO_WRITE 19		/* read only media */
#define ERR_BAD_UNIT 20		/* Unknown device */
#define ERR_NOT_READY 21		/* Drive not ready */
#define ERR_BACK_CMD 22		/* Unknown command */
#define ERR_DATA 23		/* Data (CRC) error */
#define ERR_BAD_REQ 24		/* Bad request structure length */
#define ERR_SEEK 25
#define ERR_BAD_MEDIA 26
#define ERR_BAD_SECTOR 27
#define ERR_NO_PAPER 28
#define ERR_WRITE 29		/* write fault */
#define ERR_READ 30		/* read fault */
#define ERR_GENERAL 31		/* General hardware failure */
#define ERR_WRONG_DISK 34
#define ERRFCB_UNAVAIL 35
#define ERR_SHARE_BUFEXC 36	/* share buffer exceeded */
#define ERR_DISK_FULL 39

/*
 * Access modes when opening a file
 */
#define VMFS_ACCMASK    0x0003
#define VMFS_O_RDONLY   0x0000
#define VMFS_O_WRONLY   0x0001
#define VMFS_O_RDWR 0x0002

/* values which means "don't change it" */
#define VMFS_MODE_NO_CHANGE     0xFFFFFFFF
#define VMFS_UID_NO_CHANGE      0xFFFFFFFF
#define VMFS_GID_NO_CHANGE      0xFFFFFFFF
#define VMFS_TIME_NO_CHANGE     0xFFFFFFFFFFFFFFFFULL
#define VMFS_SIZE_NO_CHANGE     0xFFFFFFFFFFFFFFFFULL

/* UNIX filetype mappings. */
#define UNIX_TYPE_FILE      0
#define UNIX_TYPE_DIR       1
#define UNIX_TYPE_SYMLINK   2
#define UNIX_TYPE_CHARDEV   3
#define UNIX_TYPE_BLKDEV    4
#define UNIX_TYPE_FIFO      5
#define UNIX_TYPE_SOCKET    6
#define UNIX_TYPE_UNKNOWN   0xFFFFFFFF

#endif /* _VMFSNO_H_ */
